#!/usr/bin/env python3
"""Generate next-app/src/lib/india-outline.ts from Natural Earth (public domain).

Source: ne_10m_admin_0_countries_ind.geojson — Natural Earth's India point-of-view
admin-0 boundaries (official Indian depiction of J&K / Ladakh), from
https://github.com/nvkelso/natural-earth-vector/tree/master/geojson

Usage: python3 -I scripts/gen_india_outline.py <path/to/ne_10m_admin_0_countries_ind.geojson>

The projection constants MUST match `project()` in next-app/src/lib/journey.ts.
"""
import json
import math
import sys
from pathlib import Path

LNG0 = 68.0
LAT_TOP = 37.5
SCALE = 10.0
COS = math.cos(math.radians(23.0))
TOLERANCE = 0.55  # in SVG units (~0.06°)
MIN_AREA = 6.0    # drop specks smaller than this (SVG units²)


def project(lng, lat):
    return ((lng - LNG0) * SCALE * COS, (LAT_TOP - lat) * SCALE)


def perp(p, a, b):
    (x, y), (x1, y1), (x2, y2) = p, a, b
    dx, dy = x2 - x1, y2 - y1
    if dx == 0 and dy == 0:
        return math.hypot(x - x1, y - y1)
    t = max(0.0, min(1.0, ((x - x1) * dx + (y - y1) * dy) / (dx * dx + dy * dy)))
    return math.hypot(x - (x1 + t * dx), y - (y1 + t * dy))


def simplify(pts, tol):
    # iterative Douglas–Peucker
    keep = [False] * len(pts)
    keep[0] = keep[-1] = True
    stack = [(0, len(pts) - 1)]
    while stack:
        s, e = stack.pop()
        best, idx = 0.0, -1
        for i in range(s + 1, e):
            d = perp(pts[i], pts[s], pts[e])
            if d > best:
                best, idx = d, i
        if best > tol:
            keep[idx] = True
            stack += [(s, idx), (idx, e)]
    return [p for p, k in zip(pts, keep) if k]


def area(pts):
    return abs(sum(x1 * y2 - x2 * y1 for (x1, y1), (x2, y2) in zip(pts, pts[1:] + pts[:1]))) / 2


def main(src):
    data = json.loads(Path(src).read_text())
    india = next(f for f in data["features"] if f["properties"].get("ADM0_A3") == "IND")
    rings = []
    for poly in india["geometry"]["coordinates"]:
        ring = [project(lng, lat) for lng, lat in poly[0]]
        if area(ring) < MIN_AREA:
            continue
        ring = simplify(ring, TOLERANCE)
        if len(ring) >= 4:
            rings.append(ring)
    rings.sort(key=area, reverse=True)
    d = " ".join(
        "M" + " L".join(f"{x:.1f} {y:.1f}" for x, y in ring) + "Z" for ring in rings
    )
    xs = [x for r in rings for x, _ in r]
    ys = [y for r in rings for _, y in r]
    out = Path(__file__).resolve().parent.parent / "next-app/src/lib/india-outline.ts"
    out.write_text(
        "// GENERATED by scripts/gen_india_outline.py — do not edit by hand.\n"
        "// Natural Earth 1:10m admin-0, India point of view (public domain).\n"
        f"// {len(rings)} rings, {sum(len(r) for r in rings)} points.\n"
        f"export const INDIA_BOUNDS = {{ width: {math.ceil(max(xs))}, height: {math.ceil(max(ys))} }} as const;\n\n"
        f'export const INDIA_PATH =\n  "{d}";\n'
    )
    print(f"wrote {out} ({len(d)} chars, {len(rings)} rings)")


if __name__ == "__main__":
    main(sys.argv[1])
